on:
  push:
    branches:
      - main
jobs:
  code-checks-web:
    uses: yuri-becker/japp/.github/workflows/code-checks.yml@main
  code-checks-server:
    uses: yuri-becker/japp/.github/workflows/code-checks.yml@main
  deploy:
    runs-on: ubuntu-latest
    needs:
      - code-checks-web
      - code-checks-server
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: "./web/pnpm-lock.yaml"
      - name: Setup cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Install web dependencies
        run: pnpm --dir web install
      - name: Build web
        run: pnpm --dir web build
      - name: Create Secrets.toml
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "./Secrets.toml"
          FILE_BASE64: ${{ secrets.SECRETS_TOML_BASE_64 }}
      - name: Build server
        run: cargo build
      - name: Login to Shuttle
        run: cargo shuttle login --api-key {{secrets.SHUTTLE_API_KEY}}
      - name: Deploy to Shuttle
        run: cargo shuttle deploy
